package router

import (
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
	"net/http"
	_ "projeto-ra-api-go/docs" // docs is generated by Swag CLI, you have to import it.
	"projeto-ra-api-go/pkg/api/controller"
)

func NewRARouter(complaint controller.ComplainCtrl, healthController *controller.HealthHandler) http.Handler {
	router := mux.NewRouter()
	router.HandleFunc("/", handleHome)
	router.HandleFunc("/complains/{id}", complaint.DeleteById).Methods("DELETE")
	router.HandleFunc("/complains/{id}", complaint.Update).Methods("PUT")
	router.HandleFunc("/complains", complaint.SaveComplain).Methods("POST")
	router.HandleFunc("/complains/{id}", complaint.FindById).Methods("GET")
	router.HandleFunc("/complains/{company}/{city}", complaint.FindByParam).Methods("GET")
	router.HandleFunc("/complains", complaint.FindByParam).Methods("GET").Queries()
	router.HandleFunc("/health", healthController.Healthcheck).Methods("GET")

	// Swagger
	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	return router
}

func handleHome(w http.ResponseWriter, r *http.Request) {
	msg := []byte("Welcome to Thiago API")
	w.Write(msg)
}
