application:
  name: ra-stack
  brand: thiago
  flow: npf

deployments:
  container:
    image:
      repository: registry.ra.com.br
      namespace: ra-dev
      name: matrix-ra-test
    resources:
      requests:
        cpu: 0.2
        memory: 512Mi
      limit:
        cpu: 0.2
        memory: 512Mi
    port: 8080
    probe:
      readiness:
        initialDelay: 5
        period: 5
      liveness:
        initialDelay: 5
        period: 5

expose:
  hosts:
    - host: ra-stack-test-go.pkg.reclameaqui.com.br
      paths:
        - /*
      ssl: false
      public: false
      config: {}

