// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RaExtApiInterface is an autogenerated mock type for the RaExtApiInterface type
type RaExtApiInterface struct {
	mock.Mock
}

// CountPageViewsRaExternalApi provides a mock function with given fields: ctx, complainName
func (_m *RaExtApiInterface) CountPageViewsRaExternalApi(ctx context.Context, complainName string) (int, error) {
	ret := _m.Called(ctx, complainName)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, complainName)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, complainName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
