basePath: /
definitions:
  model.Company:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  model.ComplainIn:
    properties:
      company:
        $ref: '#/definitions/model.Company'
        type: object
      description:
        type: string
      locale:
        $ref: '#/definitions/model.Locale'
        type: object
      title:
        type: string
    required:
    - company
    - description
    - title
    type: object
  model.ComplainOut:
    properties:
      company:
        $ref: '#/definitions/model.Company'
        type: object
      description:
        type: string
      id:
        type: string
      locale:
        $ref: '#/definitions/model.Locale'
        type: object
      countPageViews:
        type: integer
      title:
        type: string
    type: object
  model.Locale:
    properties:
      city:
        type: string
      state:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: thg.mnzs@gmail.com
    name: Thiago Menezes
  description: Ra Challenge API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ra Challenge API
  version: "1.0"
paths:
  /complains:
    get:
      consumes:
      - application/json
      description: Get details of all complains
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ComplainOut'
            type: array
      summary: Get details of all complains
      tags:
      - complains
    post:
      consumes:
      - application/json
      description: Create a new complain with the input paylod
      parameters:
      - description: Create complain
        in: body
        name: complain
        required: true
        schema:
          $ref: '#/definitions/model.ComplainIn'
      produces:
      - application/json
      responses:
        "200": {}
      summary: Create a new complain
      tags:
      - complains
swagger: "2.0"
